name: Docker Image CI

on:
  create:
    tags: 
      - '*'
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
       name: Build
       run: |
          docker build -t getcarrier/perfmeter:latest-5.4.1 -f docker/Dockerfile_v_5_4_1 .
          docker build -t getcarrier/perfmeter:latest-5.3 -f docker/Dockerfile .
          docker build -t getcarrier/perfmeter:latest-5.2.1 -f docker/Dockerfile_v_5_2_1 .
          docker build -t getcarrier/perfmeter:latest-5.2 -f docker/Dockerfile_v_5_2 .
          docker build -t getcarrier/perfmeter:latest-5.1.1 -f docker/Dockerfile_v_5_1_1 .
          docker build -t getcarrier/perfmeter:latest-5.1 -f docker/Dockerfile_v_5_1 .
          docker build -t getcarrier/perfmeter:latest-5.0 -f docker/Dockerfile_v_5_0 .
          docker build -t getcarrier/perfmeter:latest-4.0 -f docker/Dockerfile_v_4_0 .
    -
       name: Push
       run: |
         docker push getcarrier/perfmeter:latest-5.4.1
         docker push getcarrier/perfmeter:latest-5.3
         docker push getcarrier/perfmeter:latest-5.2.1
         docker push getcarrier/perfmeter:latest-5.2
         docker push getcarrier/perfmeter:latest-5.1.1
         docker push getcarrier/perfmeter:latest-5.1
         docker push getcarrier/perfmeter:latest-5.0
         docker push getcarrier/perfmeter:latest-4.0
